import type { Equipment } from '../../shared/types.ts'

export type MovementSeed = {
  name: string
  aliases?: string[]
  muscles: string[]
  equipment: Equipment[]
  youtube?: string
}

export const MOVEMENT_SEEDS: MovementSeed[] = [
  { name: 'Bench Press', muscles: ['chest', 'triceps', 'shoulders'], equipment: ['barbell', 'dumbbell', 'machine'] },
  { name: 'Incline Bench Press', muscles: ['chest', 'shoulders', 'triceps'], equipment: ['barbell', 'dumbbell', 'machine'] },
  { name: 'Decline Bench Press', muscles: ['chest', 'triceps'], equipment: ['barbell', 'dumbbell', 'machine'] },
  { name: 'Overhead Press', aliases: ['OHP', 'military press'], muscles: ['shoulders', 'triceps'], equipment: ['barbell', 'dumbbell', 'machine'] },
  { name: 'Arnold Press', muscles: ['shoulders', 'triceps'], equipment: ['dumbbell'] },
  { name: 'Lateral Raise', muscles: ['shoulders'], equipment: ['dumbbell', 'cable', 'machine'] },
  { name: 'Front Raise', muscles: ['shoulders'], equipment: ['dumbbell', 'cable', 'barbell'] },
  { name: 'Rear Delt Fly', muscles: ['shoulders'], equipment: ['dumbbell', 'cable', 'machine'] },
  { name: 'Face Pull', muscles: ['shoulders', 'upper back'], equipment: ['cable'] },
  { name: 'Push-Up', muscles: ['chest', 'triceps', 'shoulders'], equipment: ['bodyweight'] },
  { name: 'Dip', muscles: ['triceps', 'chest', 'shoulders'], equipment: ['bodyweight', 'machine'] },
  { name: 'Chest Fly', muscles: ['chest'], equipment: ['dumbbell', 'cable', 'machine'] },
  { name: 'Tricep Pushdown', muscles: ['triceps'], equipment: ['cable', 'machine'] },
  { name: 'Overhead Tricep Extension', muscles: ['triceps'], equipment: ['dumbbell', 'cable', 'barbell'] },
  { name: 'Skull Crusher', muscles: ['triceps'], equipment: ['barbell', 'dumbbell'] },
  { name: 'Close-Grip Bench Press', muscles: ['triceps', 'chest'], equipment: ['barbell'] },
  { name: 'Pull-Up', muscles: ['lats', 'biceps', 'upper back'], equipment: ['bodyweight', 'machine'] },
  { name: 'Chin-Up', muscles: ['lats', 'biceps'], equipment: ['bodyweight'] },
  { name: 'Lat Pulldown', muscles: ['lats', 'biceps'], equipment: ['cable', 'machine'] },
  { name: 'Barbell Row', aliases: ['bent over row'], muscles: ['upper back', 'lats', 'biceps'], equipment: ['barbell'] },
  { name: 'Dumbbell Row', muscles: ['lats', 'upper back', 'biceps'], equipment: ['dumbbell'] },
  { name: 'Seated Cable Row', muscles: ['upper back', 'lats', 'biceps'], equipment: ['cable', 'machine'] },
  { name: 'Chest-Supported Row', muscles: ['upper back', 'lats'], equipment: ['dumbbell', 'machine'] },
  { name: 'T-Bar Row', muscles: ['upper back', 'lats'], equipment: ['barbell', 'machine'] },
  { name: 'Shrug', muscles: ['traps'], equipment: ['barbell', 'dumbbell', 'machine'] },
  { name: 'Bicep Curl', muscles: ['biceps'], equipment: ['barbell', 'dumbbell', 'cable', 'machine'] },
  { name: 'Hammer Curl', muscles: ['biceps', 'forearms'], equipment: ['dumbbell', 'cable'] },
  { name: 'Preacher Curl', muscles: ['biceps'], equipment: ['barbell', 'dumbbell', 'machine'] },
  { name: 'Incline Curl', muscles: ['biceps'], equipment: ['dumbbell'] },
  { name: 'Back Squat', muscles: ['quads', 'glutes', 'hamstrings'], equipment: ['barbell'] },
  { name: 'Front Squat', muscles: ['quads', 'glutes', 'core'], equipment: ['barbell'] },
  { name: 'Goblet Squat', muscles: ['quads', 'glutes'], equipment: ['dumbbell', 'kettlebell'] },
  { name: 'Hack Squat', muscles: ['quads', 'glutes'], equipment: ['machine'] },
  { name: 'Leg Press', muscles: ['quads', 'glutes', 'hamstrings'], equipment: ['machine'] },
  { name: 'Lunge', muscles: ['quads', 'glutes', 'hamstrings'], equipment: ['barbell', 'dumbbell', 'bodyweight'] },
  { name: 'Walking Lunge', muscles: ['quads', 'glutes'], equipment: ['dumbbell', 'barbell', 'bodyweight'] },
  { name: 'Bulgarian Split Squat', muscles: ['quads', 'glutes'], equipment: ['dumbbell', 'barbell', 'bodyweight'] },
  { name: 'Step-Up', muscles: ['quads', 'glutes'], equipment: ['dumbbell', 'bodyweight'] },
  { name: 'Leg Extension', muscles: ['quads'], equipment: ['machine'] },
  { name: 'Romanian Deadlift', aliases: ['RDL'], muscles: ['hamstrings', 'glutes', 'lower back'], equipment: ['barbell', 'dumbbell'] },
  { name: 'Deadlift', muscles: ['hamstrings', 'glutes', 'back', 'traps'], equipment: ['barbell'] },
  { name: 'Sumo Deadlift', muscles: ['glutes', 'hamstrings', 'adductors'], equipment: ['barbell'] },
  { name: 'Trap Bar Deadlift', muscles: ['quads', 'glutes', 'hamstrings'], equipment: ['other'] },
  { name: 'Hip Thrust', muscles: ['glutes', 'hamstrings'], equipment: ['barbell', 'machine'] },
  { name: 'Glute Bridge', muscles: ['glutes'], equipment: ['barbell', 'bodyweight'] },
  { name: 'Hamstring Curl', muscles: ['hamstrings'], equipment: ['machine', 'cable'] },
  { name: 'Good Morning', muscles: ['hamstrings', 'lower back'], equipment: ['barbell'] },
  { name: 'Calf Raise', muscles: ['calves'], equipment: ['machine', 'dumbbell', 'barbell', 'bodyweight'] },
  { name: 'Seated Calf Raise', muscles: ['calves'], equipment: ['machine'] },
  { name: 'Hip Abduction', muscles: ['glutes'], equipment: ['machine', 'cable'] },
  { name: 'Hip Adduction', muscles: ['adductors'], equipment: ['machine'] },
  { name: 'Plank', muscles: ['core'], equipment: ['bodyweight'] },
  { name: 'Side Plank', muscles: ['core', 'obliques'], equipment: ['bodyweight'] },
  { name: 'Hanging Leg Raise', muscles: ['core'], equipment: ['bodyweight'] },
  { name: 'Cable Crunch', muscles: ['core'], equipment: ['cable'] },
  { name: 'Ab Wheel Rollout', muscles: ['core'], equipment: ['other'] },
  { name: 'Pallof Press', muscles: ['core', 'obliques'], equipment: ['cable'] },
  { name: 'Russian Twist', muscles: ['obliques', 'core'], equipment: ['bodyweight', 'dumbbell', 'kettlebell'] },
  { name: 'Dead Bug', muscles: ['core'], equipment: ['bodyweight'] },
  { name: 'Bird Dog', muscles: ['core', 'lower back'], equipment: ['bodyweight'] },
  { name: 'Farmer Carry', muscles: ['traps', 'forearms', 'core'], equipment: ['dumbbell', 'kettlebell', 'other'] },
  { name: 'Suitcase Carry', muscles: ['core', 'obliques', 'forearms'], equipment: ['dumbbell', 'kettlebell'] },
  { name: 'Kettlebell Swing', muscles: ['glutes', 'hamstrings', 'shoulders'], equipment: ['kettlebell'] },
  { name: 'Goblet Clean', muscles: ['full body'], equipment: ['kettlebell'] },
  { name: 'Turkish Get-Up', muscles: ['full body', 'core'], equipment: ['kettlebell', 'dumbbell'] },
  { name: 'Thruster', muscles: ['quads', 'shoulders', 'core'], equipment: ['barbell', 'dumbbell', 'kettlebell'] },
  { name: 'Clean', muscles: ['full body'], equipment: ['barbell'] },
  { name: 'Power Clean', muscles: ['full body'], equipment: ['barbell'] },
  { name: 'Snatch', muscles: ['full body'], equipment: ['barbell'] },
  { name: 'Push Press', muscles: ['shoulders', 'triceps', 'legs'], equipment: ['barbell', 'dumbbell'] },
  { name: 'Landmine Press', muscles: ['shoulders', 'chest'], equipment: ['barbell'] },
  { name: 'Landmine Row', muscles: ['upper back', 'lats'], equipment: ['barbell'] },
  { name: 'Pec Deck', muscles: ['chest'], equipment: ['machine'] },
  { name: 'Smith Machine Squat', muscles: ['quads', 'glutes'], equipment: ['machine'] },
  { name: 'Pendlay Row', muscles: ['upper back', 'lats'], equipment: ['barbell'] },
  { name: 'Inverted Row', muscles: ['upper back', 'biceps'], equipment: ['bodyweight'] },
  { name: 'Nordic Hamstring Curl', muscles: ['hamstrings'], equipment: ['bodyweight'] },
  { name: 'Sissy Squat', muscles: ['quads'], equipment: ['bodyweight', 'machine'] },
  { name: 'Belt Squat', muscles: ['quads', 'glutes'], equipment: ['machine'] },
  { name: 'Wrist Curl', muscles: ['forearms'], equipment: ['barbell', 'dumbbell'] },
  { name: 'Reverse Wrist Curl', muscles: ['forearms'], equipment: ['barbell', 'dumbbell'] },
  { name: 'Box Squat', muscles: ['quads', 'glutes'], equipment: ['barbell'] },
  { name: 'Pause Squat', muscles: ['quads', 'glutes'], equipment: ['barbell'] },
  { name: 'Floor Press', muscles: ['chest', 'triceps'], equipment: ['barbell', 'dumbbell'] },
  { name: 'JM Press', muscles: ['triceps'], equipment: ['barbell'] },
  { name: 'Spoto Press', muscles: ['chest', 'triceps'], equipment: ['barbell'] },
  { name: 'Meadows Row', muscles: ['lats', 'upper back'], equipment: ['barbell'] },
  { name: 'Cable Lateral Raise', muscles: ['shoulders'], equipment: ['cable'] },
  { name: 'Y Raise', muscles: ['shoulders', 'upper back'], equipment: ['dumbbell', 'cable'] },
  { name: 'Copenhagen Plank', muscles: ['adductors', 'core'], equipment: ['bodyweight'] },
  { name: 'Single-Leg RDL', muscles: ['hamstrings', 'glutes'], equipment: ['dumbbell', 'kettlebell', 'barbell'] },
  { name: 'Cossack Squat', muscles: ['quads', 'adductors'], equipment: ['bodyweight', 'kettlebell'] },
  { name: 'Muscle-Up', muscles: ['lats', 'chest', 'triceps'], equipment: ['bodyweight'] },
  { name: 'Handstand Push-Up', muscles: ['shoulders', 'triceps'], equipment: ['bodyweight'] },
  { name: 'Pistol Squat', muscles: ['quads', 'glutes'], equipment: ['bodyweight'] },
]
